
import React, { useState, useEffect } from 'react';
import { 
  User, Phone, MapPin, Sprout, ArrowRight, ShieldCheck, LogOut, Settings, 
  Bell, MessageSquare, Plus, Edit, Trash2, Calendar, Syringe, Clock, 
  CloudSun, Save, X, Activity, AlertCircle, CheckCircle2, LayoutDashboard,
  ChevronRight, AlertTriangle, Timer
} from 'lucide-react';
// Fix: Use a more robust import pattern for react-router-dom to handle environment-specific export issues
import * as ReactRouterDOM from 'react-router-dom';
const { Link } = ReactRouterDOM as any;
import { getDistrictWeather } from '../services/gemini';

type PortalTab = 'dashboard' | 'sprays' | 'reminders' | 'profile';

const FarmerLogin: React.FC = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(() => !!localStorage.getItem('fck_farmer_session'));
  const [farmer, setFarmer] = useState(() => {
    const saved = localStorage.getItem('fck_farmer_profile');
    return saved ? JSON.parse(saved) : null;
  });
  
  const [activeTab, setActiveTab] = useState<PortalTab>('dashboard');
  const [weather, setWeather] = useState<any>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<any>(null);
  
  // Data State with Time Tracking
  const [sprays, setSprays] = useState<any[]>(() => JSON.parse(localStorage.getItem('fck_pesticide_logs') || '[]'));
  const [reminders, setReminders] = useState<any[]>(() => JSON.parse(localStorage.getItem('fck_farmer_reminders') || '[]'));

  useEffect(() => {
    localStorage.setItem('fck_pesticide_logs', JSON.stringify(sprays));
    localStorage.setItem('fck_farmer_reminders', JSON.stringify(reminders));
  }, [sprays, reminders]);

  useEffect(() => {
    if (isLoggedIn && farmer) {
      getDistrictWeather(farmer.location || 'Srinagar').then(setWeather).catch(() => {});
    }
  }, [isLoggedIn, farmer]);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    // Simulated login for demo purposes
    const mockFarmer = {
      id: 'F-101',
      name: 'Mohammad Yusuf',
      phone: '9419012345',
      orchardName: 'Yusuf Apple Estates',
      location: 'Sopore',
      crops: ['Apple', 'Walnut'],
      lastLogin: new Date().toISOString()
    };
    localStorage.setItem('fck_farmer_session', 'active');
    localStorage.setItem('fck_farmer_profile', JSON.stringify(mockFarmer));
    setFarmer(mockFarmer);
    setIsLoggedIn(true);
  };

  const deleteItem = (id: string, type: 'spray' | 'reminder') => {
    if (!window.confirm("Delete this record permanently?")) return;
    if (type === 'spray') setSprays(prev => prev.filter(i => i.id !== id));
    if (type === 'reminder') setReminders(prev => prev.filter(i => i.id !== id));
  };

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget as HTMLFormElement);
    const data: any = Object.fromEntries(formData.entries());
    const id = editingItem?.id || Date.now().toString();
    const newItem = { ...data, id };

    if (activeTab === 'sprays') {
      setSprays(prev => editingItem ? prev.map(i => i.id === id ? newItem : i) : [newItem, ...prev]);
      
      // Auto-schedule reminder logic
      if (data.autoRemind === 'on' && !editingItem) {
        const intervalMap: Record<string, number> = {
          'Contact': 8,
          'Systemic': 10,
          'Combination': 12,
          'Insecticide': 15
        };
        const daysToAdd = intervalMap[data.type] || 10;
        const sprayDate = new Date(data.date);
        sprayDate.setDate(sprayDate.getDate() + daysToAdd);
        const nextDateStr = sprayDate.toISOString().split('T')[0];

        const reminderItem = {
          id: Date.now().toString() + '_auto',
          date: nextDateStr,
          time: '09:00',
          task: `Follow-up: ${data.chemicalName} (${data.type} Cycle)`,
          autoGenerated: true
        };
        setReminders(prev => [reminderItem, ...prev]);
        alert(`Reminder automatically set for ${nextDateStr} (${daysToAdd} days later).`);
      }

    } else if (activeTab === 'reminders') {
      setReminders(prev => editingItem ? prev.map(i => i.id === id ? newItem : i) : [newItem, ...prev]);
    } else if (activeTab === 'profile') {
      const updatedFarmer = { ...farmer, ...data };
      setFarmer(updatedFarmer);
      localStorage.setItem('fck_farmer_profile', JSON.stringify(updatedFarmer));
    }

    setIsModalOpen(false);
  };

  const getOverdueStatus = (dateStr: string, timeStr: string) => {
    const due = new Date(`${dateStr}T${timeStr || '23:59'}`);
    const now = new Date();
    return due < now;
  };

  if (isLoggedIn && farmer) {
    return (
      <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-700 pb-20 no-scrollbar">
        {/* Profile Header */}
        <header className="bg-emerald-900 rounded-[3rem] p-8 lg:p-12 text-white relative overflow-hidden shadow-2xl">
          <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="flex items-center gap-6">
              <div className="w-20 h-20 bg-white/10 rounded-[2rem] flex items-center justify-center border border-white/20 shadow-xl">
                <User className="w-10 h-10 text-emerald-400" />
              </div>
              <div>
                <h2 className="text-4xl font-bold font-heading">{farmer.name}</h2>
                <div className="flex flex-wrap gap-4 mt-2">
                  <span className="flex items-center gap-2 text-xs font-bold text-emerald-300"><MapPin className="w-3 h-3" /> {farmer.location}</span>
                  <span className="flex items-center gap-2 text-xs font-bold text-emerald-300"><Sprout className="w-3 h-3" /> {farmer.orchardName}</span>
                </div>
              </div>
            </div>
            <div className="flex gap-3">
              <button onClick={() => {localStorage.removeItem('fck_farmer_session'); setIsLoggedIn(false);}} className="p-4 bg-white/10 hover:bg-rose-500/40 rounded-2xl transition-all"><LogOut className="w-6 h-6" /></button>
            </div>
          </div>
          <Activity className="absolute -bottom-10 -right-10 w-48 h-48 text-white/5 pointer-events-none" />
        </header>

        {/* Navigation Tabs */}
        <div className="flex gap-2 overflow-x-auto no-scrollbar bg-white/50 p-2 rounded-3xl border border-slate-100">
          {[
            { id: 'dashboard', label: 'My Hub', icon: LayoutDashboard },
            { id: 'sprays', label: 'Sprays', icon: Syringe },
            { id: 'reminders', label: 'Tasks & Alerts', icon: Bell },
            { id: 'profile', label: 'Settings', icon: Settings }
          ].map(tab => (
            <button key={tab.id} onClick={() => setActiveTab(tab.id as PortalTab)} className={`flex items-center gap-3 px-6 py-3 rounded-2xl font-black text-[10px] uppercase tracking-widest transition-all border ${activeTab === tab.id ? 'bg-emerald-900 text-white border-emerald-900 shadow-lg' : 'bg-white text-slate-500 border-slate-100'}`}><tab.icon className="w-4 h-4" /> {tab.label}</button>
          ))}
        </div>

        <div className="min-h-[500px]">
          {/* Dashboard View */}
          {activeTab === 'dashboard' && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
               <div className="md:col-span-2 bg-emerald-950 p-8 rounded-[3rem] text-white shadow-xl relative overflow-hidden flex flex-col justify-between">
                 <div className="relative z-10 flex flex-col md:flex-row justify-between items-start gap-6">
                    <div>
                      <h3 className="text-xl font-bold flex items-center gap-3"><Syringe className="w-5 h-5 text-emerald-400" /> Active Stage: Pink Bud</h3>
                      <p className="text-emerald-200/70 text-sm mt-2 font-medium max-w-md">The 3rd stage of the SKUAST-K protocol is currently active in the valley.</p>
                      <div className="mt-6 flex flex-wrap gap-3">
                         <div className="bg-white/10 px-4 py-2 rounded-xl text-xs font-bold border border-white/5">Molecule: Mancozeb / Zineb</div>
                         <div className="bg-emerald-600 px-4 py-2 rounded-xl text-xs font-bold shadow-lg">Due: Apr 05 - Apr 15</div>
                      </div>
                    </div>
                    <Link to="/spray-track" className="bg-white text-emerald-900 px-6 py-3 rounded-xl font-bold text-xs uppercase tracking-widest flex items-center gap-2 hover:bg-emerald-50 transition-colors">
                      Open 8-Stage Tracker <ChevronRight className="w-4 h-4" />
                    </Link>
                 </div>
                 <Activity className="absolute -bottom-10 -right-10 w-48 h-48 text-white/5 pointer-events-none" />
               </div>

              <div className="bg-white p-8 rounded-[3rem] border border-slate-100 shadow-sm space-y-6">
                <div className="flex justify-between items-center"><h3 className="font-bold text-lg">Local Climate</h3><CloudSun className="text-emerald-600" /></div>
                {weather ? (
                  <div className="text-center py-4">
                    <p className="text-5xl font-black text-slate-900">{weather.temperature}</p>
                    <p className="text-sm font-bold text-slate-500 uppercase mt-2">{weather.condition}</p>
                  </div>
                ) : <div className="animate-pulse h-20 bg-slate-100 rounded-2xl" />}
                <p className="text-xs text-slate-400 leading-relaxed italic">"{weather?.farmerTip || 'Loading valley intelligence...'}"</p>
              </div>

              <div className="bg-white p-8 rounded-[3rem] border border-slate-100 shadow-sm space-y-6 md:col-span-3">
                <div className="flex justify-between items-center"><h3 className="font-bold text-lg">Recent Logs</h3><ShieldCheck className="text-emerald-600" /></div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  {sprays.slice(0, 3).map(s => (
                    <div key={s.id} className="bg-slate-50 border border-slate-100 p-4 rounded-2xl flex items-center gap-4">
                      <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center"><Syringe className="w-5 h-5 text-emerald-600" /></div>
                      <div>
                        <p className="font-bold text-sm text-slate-900">{s.chemicalName}</p>
                        <p className="text-[10px] text-slate-500 uppercase font-black">{s.date}</p>
                      </div>
                    </div>
                  ))}
                  {sprays.length === 0 && <p className="text-sm text-slate-400 italic">No sprays logged yet.</p>}
                </div>
                <button onClick={() => setActiveTab('sprays')} className="w-full py-4 bg-slate-900 text-white rounded-2xl font-bold text-xs uppercase tracking-widest shadow-lg hover:bg-black transition-colors">Manage Full History</button>
              </div>
            </div>
          )}

          {/* Sprays CRUD View */}
          {activeTab === 'sprays' && (
            <div className="bg-white rounded-[3rem] border border-slate-100 p-8 space-y-6">
              <div className="flex justify-between items-center">
                <h3 className="text-2xl font-bold flex items-center gap-3"><Syringe className="text-emerald-600" /> Application History</h3>
                <button onClick={() => {setEditingItem(null); setIsModalOpen(true);}} className="bg-emerald-600 text-white px-6 py-3 rounded-2xl font-bold text-xs uppercase tracking-widest flex items-center gap-2"><Plus className="w-4 h-4" /> Log Spray</button>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-left">
                  <thead><tr className="text-[10px] font-black uppercase text-slate-400 tracking-widest border-b"><th className="pb-4">Date/Time</th><th className="pb-4">Chemical</th><th className="pb-4">Brand</th><th className="pb-4">Type</th><th className="pb-4 text-right">Admin</th></tr></thead>
                  <tbody className="divide-y">
                    {sprays.map(s => (
                      <tr key={s.id} className="group hover:bg-slate-50 transition-all">
                        <td className="py-5">
                          <p className="font-bold text-slate-900">{s.date}</p>
                          <p className="text-[10px] font-black text-slate-400 uppercase">{s.time || '--:--'}</p>
                        </td>
                        <td className="py-5 font-black text-slate-700">{s.chemicalName}</td>
                        <td className="py-5 text-xs text-slate-500 uppercase font-bold">{s.brandName || '---'}</td>
                        <td className="py-5"><span className="bg-emerald-50 text-emerald-700 px-3 py-1 rounded-lg text-[9px] font-black">{s.type}</span></td>
                        <td className="py-5 text-right flex justify-end gap-2">
                           <button onClick={() => {setEditingItem(s); setIsModalOpen(true);}} className="p-2 text-emerald-600 hover:bg-white rounded-lg"><Edit className="w-4 h-4" /></button>
                           <button onClick={() => deleteItem(s.id, 'spray')} className="p-2 text-rose-600 hover:bg-white rounded-lg"><Trash2 className="w-4 h-4" /></button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Reminders CRUD View */}
          {activeTab === 'reminders' && (
            <div className="bg-white rounded-[3rem] border border-slate-100 p-8 space-y-6">
              <div className="flex justify-between items-center">
                <h3 className="text-2xl font-bold flex items-center gap-3"><Bell className="text-amber-500" /> Reminders & Tasks</h3>
                <button onClick={() => {setEditingItem(null); setIsModalOpen(true);}} className="bg-amber-500 text-white px-6 py-3 rounded-2xl font-bold text-xs uppercase tracking-widest flex items-center gap-2"><Plus className="w-4 h-4" /> Add Task</button>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {reminders.map(r => {
                  const isOverdue = getOverdueStatus(r.date, r.time);
                  return (
                    <div key={r.id} className={`p-6 rounded-[2rem] border flex items-center justify-between group transition-all ${isOverdue ? 'bg-rose-50 border-rose-200' : 'bg-slate-50 border-slate-100'}`}>
                      <div className="flex items-center gap-5">
                        <div className={`p-3 rounded-2xl shadow-sm ${isOverdue ? 'bg-white text-rose-500 animate-pulse' : 'bg-white text-slate-400'}`}>
                          {isOverdue ? <AlertTriangle className="w-5 h-5" /> : <Clock className="w-5 h-5" />}
                        </div>
                        <div>
                          {isOverdue && <span className="text-[8px] font-black text-rose-600 uppercase tracking-widest bg-white px-2 py-0.5 rounded mb-1 inline-block">Missed Spray</span>}
                          <p className={`font-bold ${isOverdue ? 'text-rose-900' : 'text-slate-900'}`}>{r.task}</p>
                          <p className={`text-[10px] font-black uppercase mt-1 ${isOverdue ? 'text-rose-700' : 'text-amber-600'}`}>Due: {r.date} @ {r.time || 'All Day'}</p>
                        </div>
                      </div>
                      <div className="flex gap-2 opacity-0 group-hover:opacity-100 transition-all">
                        <button onClick={() => {setEditingItem(r); setIsModalOpen(true);}} className="p-2 text-emerald-600 bg-white rounded-xl shadow-sm hover:scale-110 transition-transform"><Edit className="w-4 h-4" /></button>
                        <button onClick={() => deleteItem(r.id, 'reminder')} className="p-2 text-rose-600 bg-white rounded-xl shadow-sm hover:scale-110 transition-transform"><Trash2 className="w-4 h-4" /></button>
                      </div>
                    </div>
                  );
                })}
                {reminders.length === 0 && <p className="text-slate-400 font-medium text-sm italic col-span-2 text-center py-10">No pending tasks.</p>}
              </div>
            </div>
          )}

          {/* Profile CRUD View */}
          {activeTab === 'profile' && (
             <div className="bg-white rounded-[3rem] border border-slate-100 p-8 space-y-6">
               <div className="flex justify-between items-center">
                 <h3 className="text-2xl font-bold flex items-center gap-3"><Settings className="text-slate-600" /> Profile Settings</h3>
                 <button onClick={() => {setEditingItem(farmer); setIsModalOpen(true);}} className="bg-slate-900 text-white px-6 py-3 rounded-2xl font-bold text-xs uppercase tracking-widest flex items-center gap-2"><Edit className="w-4 h-4" /> Edit Profile</button>
               </div>
               <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="p-6 bg-slate-50 rounded-[2rem]">
                    <span className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Full Name</span>
                    <p className="text-xl font-bold text-slate-900">{farmer.name}</p>
                  </div>
                  <div className="p-6 bg-slate-50 rounded-[2rem]">
                    <span className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Orchard Name</span>
                    <p className="text-xl font-bold text-slate-900">{farmer.orchardName}</p>
                  </div>
                  <div className="p-6 bg-slate-50 rounded-[2rem]">
                    <span className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Phone</span>
                    <p className="text-xl font-bold text-slate-900">{farmer.phone}</p>
                  </div>
                  <div className="p-6 bg-slate-50 rounded-[2rem]">
                    <span className="text-[10px] font-black uppercase text-slate-400 tracking-widest">District</span>
                    <p className="text-xl font-bold text-slate-900">{farmer.location}</p>
                  </div>
               </div>
             </div>
          )}
        </div>

        {/* Unified Modal for All Actions */}
        {isModalOpen && (
          <div className="fixed inset-0 z-[300] flex items-center justify-center p-6 backdrop-blur-md bg-slate-900/40">
            <div className="bg-white w-full max-w-lg rounded-[3rem] shadow-2xl p-10 space-y-8 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto">
              <div className="flex justify-between items-center"><h3 className="text-2xl font-bold">Manage {activeTab === 'profile' ? 'Profile' : activeTab.slice(0, -1)}</h3><button onClick={() => setIsModalOpen(false)} className="p-2"><X className="w-6 h-6 text-slate-400" /></button></div>
              <form onSubmit={handleSave} className="space-y-6">
                
                {activeTab === 'sprays' && (<>
                  <div className="flex gap-4">
                    <div className="flex-1">
                      <label className="text-[10px] font-black uppercase text-slate-400">Date</label>
                      <input name="date" type="date" defaultValue={editingItem?.date || new Date().toISOString().split('T')[0]} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" required />
                    </div>
                    <div className="flex-1">
                      <label className="text-[10px] font-black uppercase text-slate-400">Time</label>
                      <input name="time" type="time" defaultValue={editingItem?.time || '09:00'} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" required />
                    </div>
                  </div>
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400">Chemical / Molecule</label>
                    <input name="chemicalName" placeholder="e.g. Mancozeb" defaultValue={editingItem?.chemicalName} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" required />
                  </div>
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400">Brand Name</label>
                    <input name="brandName" placeholder="e.g. M-45" defaultValue={editingItem?.brandName} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" />
                  </div>
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400">Type</label>
                    <select name="type" defaultValue={editingItem?.type} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold">
                      <option value="Contact">Contact Fungicide (8 days)</option>
                      <option value="Systemic">Systemic Fungicide (10 days)</option>
                      <option value="Combination">Combination (12 days)</option>
                      <option value="Insecticide">Insecticide (15 days)</option>
                    </select>
                  </div>
                  {!editingItem && (
                    <div className="flex items-center gap-3 p-4 bg-emerald-50 rounded-2xl border border-emerald-100">
                      <input type="checkbox" name="autoRemind" className="w-5 h-5 text-emerald-600 rounded focus:ring-emerald-500" defaultChecked />
                      <div className="flex-1">
                        <label className="font-bold text-sm text-emerald-900 block">Auto-schedule Reminder</label>
                        <p className="text-[10px] text-emerald-700">Set task for next spray based on type.</p>
                      </div>
                      <Timer className="w-5 h-5 text-emerald-600" />
                    </div>
                  )}
                </>)}

                {activeTab === 'reminders' && (<>
                  <div className="flex gap-4">
                    <div className="flex-1">
                      <label className="text-[10px] font-black uppercase text-slate-400">Date</label>
                      <input name="date" type="date" defaultValue={editingItem?.date || new Date().toISOString().split('T')[0]} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" required />
                    </div>
                    <div className="flex-1">
                      <label className="text-[10px] font-black uppercase text-slate-400">Time</label>
                      <input name="time" type="time" defaultValue={editingItem?.time || '10:00'} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" required />
                    </div>
                  </div>
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400">Task Description</label>
                    <input name="task" placeholder="e.g. Check irrigation, Buy urea" defaultValue={editingItem?.task} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" required />
                  </div>
                </>)}

                {activeTab === 'profile' && (<>
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400">Farmer Name</label>
                    <input name="name" defaultValue={farmer.name} placeholder="Name" className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" />
                  </div>
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400">Orchard Name</label>
                    <input name="orchardName" defaultValue={farmer.orchardName} placeholder="Orchard Name" className="w-full p-4 bg-slate-50 border rounded-2xl font-bold" />
                  </div>
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400">District</label>
                    <select name="location" defaultValue={farmer.location} className="w-full p-4 bg-slate-50 border rounded-2xl font-bold">
                      <option>Srinagar</option><option>Sopore</option><option>Shopian</option><option>Anantnag</option><option>Baramulla</option><option>Pulwama</option><option>Kupwara</option><option>Budgam</option><option>Ganderbal</option><option>Kulgam</option>
                    </select>
                  </div>
                </>)}

                <button className="w-full bg-emerald-600 text-white py-5 rounded-[2rem] font-bold shadow-xl flex items-center justify-center gap-2 hover:bg-emerald-700 transition-all"><Save className="w-5 h-5" /> Save Changes</button>
              </form>
            </div>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="min-h-[70vh] flex items-center justify-center p-6">
      <div className="bg-white w-full max-w-md rounded-[3rem] shadow-2xl border border-slate-100 p-10 space-y-8 animate-in zoom-in-95">
        <div className="text-center space-y-4">
          <div className="w-20 h-20 bg-emerald-900 text-white rounded-3xl flex items-center justify-center mx-auto shadow-xl"><User className="w-10 h-10" /></div>
          <h2 className="text-3xl font-heading font-bold text-slate-900">Farmer Portal</h2>
          <p className="text-slate-500 font-medium">Your personalized agri-command hub.</p>
        </div>
        <form onSubmit={handleLogin} className="space-y-4">
          <input type="tel" placeholder="9419XXXXXX" required className="w-full bg-slate-50 border border-slate-200 rounded-2xl py-4 px-6 outline-none focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 transition-all font-bold" />
          <button className="w-full bg-emerald-900 text-white py-4 rounded-2xl font-bold shadow-xl flex items-center justify-center gap-3">Authorize & Enter <ArrowRight className="w-5 h-5" /></button>
        </form>
        <div className="pt-6 border-t border-slate-50 flex items-center justify-center gap-2 text-emerald-600 font-bold text-xs uppercase tracking-widest"><ShieldCheck className="w-4 h-4" /> Secure J&K Node</div>
      </div>
    </div>
  );
};

export default FarmerLogin;
